Add debug messages to manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -18,7 +18,8 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install --force-reinstall -r requirements.txt
+        pip install --force-reinstall -r requirements.txt || true
+        pip freeze | grep pandas || echo "Pandas NOT found"
     - name: Verify installed packages
       run: |
         pip freeze
